[project]
name = "cp-genie"
version = "0.1.0"
description = "RAG chatbot system for CP chula"
authors = [
    {name = "Thiraput01",email = "Thiraputball@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "langchain>=0.1.18",
    "langchain-google-genai",
    "langchain-huggingface",
    "langchain-qdrant",
    "langchain-community",
    "langchain-core",
    "langgraph",
    "redis",
    "langchain-redis",
    "sentence-transformers",
    "qdrant-client",
    "fastembed",
    "datasets",
    "pandas",
    "tqdm",
    "requests",
    "beautifulsoup4",
    "python-dotenv",
    "fastapi",
    "uvicorn",
    "lxml (>=5.4.0,<6.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "pdf2image (>=1.17.0,<2.0.0)",
    "pytesseract (>=0.3.13,<0.4.0)",
    "langchain-google-vertexai (>=2.0.23,<3.0.0)",
    "streamlit (>=1.45.0,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
include = [
  { path = "src/cp_genie/py.typed" }
]

packages = [
    { include = "cp_genie", from = "src" }
]

# Ruff
[tool.ruff]
fix = true
indent-width = 4
line-length = 100
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D100", "D103"]


# Checks
[tool.poetry.group.checks]
optional = true

[tool.poetry.group.checks.dependencies]
ruff = "^0.4.0"
mypy = "^1.8.0"
pytest = "^8.1.1"


[tool.poetry.scripts]
start = "run:main"
streamlit = "streamlit:run"

[tool.poetry.group.dev.dependencies]
jupyter = "*"
ipykernel = "*"
black = "*"
isort = "*"
pytest = "*"